2018-12-22 09:46:36 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.douban.com/>
Traceback (most recent call last):
  File "d:\veryimportant\pythonprojects\flask\movieproject\venv\lib\site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "d:\veryimportant\pythonprojects\flask\movieproject\venv\lib\site-packages\twisted\python\failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "d:\veryimportant\pythonprojects\flask\movieproject\venv\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
